const ADD_MORE_FILE = 'ADD_MORE_FILE'
const UPLOAD_FILE = 'UPLOAD_FILE'
const UPLOAD_DOC_TO_DRIVE = 'UPLOAD_DOC_TO_DRIVE'

export default {
    ADD_MORE_FILE,
    UPLOAD_FILE,
    UPLOAD_DOC_TO_DRIVE,
}