export { default as Home } from './home.screen'
export { default as Explore } from './explore.screen'
export { default as AddDocument } from './add.screen'
export { default as Profile } from './profile.screen'
export { default as Camera } from './camera.screen'
export { default as Processing } from './processing.screen'
export { default as Register } from './register.screen'
export { default as Login } from './login.screen'
