export { default as Home } from './Home'
export { default as AddDocument } from './AddDocument'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Profile } from './Profile'
export { default as Explore } from './Explore'
export { default as DocumentDetails } from './DocumentDetails'
export { default as CameraScreen } from './CameraScreen'